# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingCart', '0002_auto_20170323_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.CharField(default='ps4.jpg', max_length=30),
            preserve_default=False,
        ),
    ]
